### PR TITLE
You may be interrested.

### PR DESCRIPTION
**Pull request by mojocorp**
Hi,

I had to do some changes for a project and I think it could be interresting to merge.
Just close the pull request if you are not interreted.

Thanks,
Morgan

### CODE REVIEW

**Comment by maxint-rd** [comment]
Hello Morgan,
I just saw your pull request (somehow missed an e-mail notification). I am definitely interested in your changes and very much appreciate your contribution. Additionally, I've been working on making this library support the ATmega328 based Arduinos (Uno, Nano, Pro Mini, etc.) and have working code that still needs some cleanup. If I can find some time soon to review your changes, I will merge the pull request asap. 
Thank you once more for working on this library!

Cheers,

Marcel

**Comment by maxint-rd** [comment]
I just tested it on an ESP-12E and saw no issues. The callback works great, so I committed your pull request and  I'm also adding or updating example to demonstrate this feature. Thanks!

**Comment by mojocorp** [comment]
Thanks.
This library add a lot of fun to small robots and is super easy to integrate. The big missing piece in my opinion are sound effects. Melodies are quite easy to find with the link you put on the Readme but for bips blups pew pew R2D2 like, etc...hum I didn't find anything so far. Don't hesitate to put more links since I'm now spending a lot of time trying to find some.
Thanks again.

**Comment by maxint-rd** [comment]
Hi Morgan, just to let you know; I just committed a new version that has support for ATmega328/168 and similar Arduino's. I also included a new example that produces some simple sound effects.
It's not very sophisticated code, but it may be enough for some purposes.

BTW, I probably will rename the library in github as it isn't exclusive for ESP8266 anymore.

**Pull request merged**
